### PR TITLE
feat: use new vib finalize plugins to create functional iso

### PR DESCRIPTION
**Pull request by axtloss**
~~this is still work in progress, includes some left overs of me experimenting with arch, and gdm doesn't automatically log in, making it impossible to actually get into any session~~ The iso is fully functional and can be used to install vanilla os

TODO:
- [x] gdm autologin
- [x] functional vanilla-installer
- [x] reduce size to be comparable to our current iso (~1.7gb)
- [ ] ~~fix vib recipe to allow build layer caching~~

### CODE REVIEW

**Comment by axtloss** [comment]
It's now possible to use the produced iso to install vanilla os, the installer is fully usable and gdm automatically logs into the installer session
the iso currently is 2.5gb big, the one produced by https://github.com/Vanilla-OS/live-iso is 1.7gb big, I'd like to try and see if I can reduce the size of this built iso before merging

**Comment by axtloss** [comment]
The vib recipe currently also doesn't allow for podman/docker to cache the build layers, since the source changes every time. Fixing this won't be a blocker to this pr since the CI wouldn't be able to use the cache either way, but I'll try to fix this nonetheless, since it can get pretty annoying to sit through the entire build even if layers haven't changed at all

**Comment by axtloss** [comment]
The iso is now 1.8gb big
instead of basing the image on core-image, it uses pico as the base and pulls modules from core-image that are required for it to boot. core-image contains dependencies that we don't need in the installer, such as abroot or apx.

**Comment by axtloss** [comment]
Fixing the vib recipe to allow caching would require some changes in other software, which is why im ignoring that part for now
this pr can be merged now.

**Review by mirkobrombin — APPROVED** [review]

**Pull request merged**
